### ISSUE TITLE
Document.MapFragment does not seem to handle some data types

### ISSUE THREAD

**Issue by leddt** [adaptivewebworks/prismicio-netstandard-kit#16]
I'm trying to migrate from the .net framework prismicio package and I've hit a blocking issue. I'm using version 2.0.1.

The results of one of my query are missing a property that should have been included through fetch links. The same query works correctly with the .net framework version.

I debugged the code and it seems that `Document.MapFragment` is not handling some types of data correctly. See screenshot:
![image](https://user-images.githubusercontent.com/239219/99078130-d6d69100-258b-11eb-8b11-dbd563b746be.png)

The field does not have a `value` property, so `FragmentParser.Parse` received null. This field comes from a nested document link and is included through fetch links.

I can't share the prismic repository for confidentiality reasons, but here is the request that is being sent to prismic:
```
https://myrepo.cdn.prismic.io/api/v1/documents/search
  ?page=1
  &pageSize=1
  &access_token=REDACTED
  &ref=X61WpRIAACAAP5AJ&q=%5B%5B%3Ad+%3D+at(document.type%2C+%22conformity-indicator-enterprise-list%22)%5D%5D
  &lang=fr-ca
  &fetchLinks=indicator.title%2Cindicator.apply_project_status_explore%2Cindicator.apply_eem_native_communities%2Cindicator.apply_eem_stakeholders
```

And a snippet of the response returned:

```
         "body": {
            "type": "SliceZone",
            "value": [
              {
                "type": "Slice",
                "slice_type": "groupe_d_indicateurs",
                "slice_label": null,
                "repeat": [
                  {
                    "indicators": {
                      "type": "Link.document",
                      "value": {
                        "document": {
                          "id": "Xea7dhEAACUAmxFy",
                          "type": "indicator",
                          "tags": [],
                          "lang": "fr-ca",
                          "slug": "4.-exigences-legales",
                          "uid": "4",
                          "data": {
                            "indicator": {
                              "title": [
                                {
                                  "type": "heading1",
                                  "text": "4. Exigences légales",
                                  "spans": []
                                }
                              ],
                              "apply_project_status_explore": {
                                "type": "Select",
                                "value": "Oui"
                              },
                              "apply_fs_native_communities": {
                                "type": "Select",
                                "value": "Oui"
                              },
                              "apply_fs_other_stakeholders": {
                                "type": "Select",
                                "value": "Oui"
                              }
                            }
                          }
                        },
                        "isBroken": false
                      }
                    }
                  }
                ]
```

In the end it's my `indicator.title` fetch link that is missing in my final results, but the other properties (`apply_*`) are present.

**Comment by benembery** [comment]
Thanks for raising this issue, I'm sorry your having difficulty.
Is there any chance you could send my a redacted version of a full document response, please. I can use that as the basis for a fixture to prove the fix.

Then I can put out a pre-release version for you to test the fix.

**Comment by benembery** [comment]
@leddt, I may actually have a fix already.

**Comment by benembery** [comment]
@leddt could you please try this pre-release package.

```shell
dotnet add package prismicio.netstandard --version 2.0.2-pre.20201113.4
```

**Comment by leddt** [comment]
@benembery just tested and it looks like it's working! Thanks!!

**Comment by benembery** [comment]
Great news, I removed something I shouldn't have when I was refactoring. At least it's covered with tests now 👍. I appreciate your help. 

I'll hopefully have a chance to test it myself over the weekend. If all goes well I'll release version 2.0.2.

How are you finding the migration otherwise? I appreciate there are quite a few differences, that I really need to find time to document.

**Comment by leddt** [comment]
Very smooth. Most of our prismic code is enclosed in a single service so the changes were centralized there, and even then it was mostly a case of capitalizing method calls. The biggest change was that I removed some code that we had, since we had made our own "prismic API accessor" that I replaced with yours. Very happy overall.

**Comment by leddt** [comment]
Hey @benembery I was wondering if you were planning to release version 2.0.2 soon? I'd like to use a non-prerelease version in my project, if possible. Thanks!

**Comment by benembery** [comment]
Hi @leddt, sorry I haven't had a chance to test it with the project your working on. Since, I've heard no complaints from you, I've released this, it should be available soon.
